#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardQHQT.DBConnection
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TuyenSinhDashboardQHQT")]
	public partial class TuyenSinhDashboardQHQTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TuyenSinhDashboardQHQTDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TuyenSinhDashboardQHQTConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TuyenSinhDashboardQHQTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TuyenSinhDashboardQHQTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TuyenSinhDashboardQHQTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TuyenSinhDashboardQHQTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_coso_select_all")]
		public ISingleResult<sp_dim_coso_select_allResult> sp_dim_coso_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_dim_coso_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_tonghop_nguontiepcan")]
		public ISingleResult<sp_tonghop_nguontiepcanResult> sp_tonghop_nguontiepcan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhuVuc", DbType="NVarChar(50)")] string maKhuVuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNguon", DbType="NVarChar(50)")] string maNguon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam, maKhuVuc, maNguon);
			return ((ISingleResult<sp_tonghop_nguontiepcanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_hinhthuctuyensinh_select_all")]
		public ISingleResult<sp_dim_hinhthuctuyensinh_select_allResult> sp_dim_hinhthuctuyensinh_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_dim_hinhthuctuyensinh_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_khuvuc_select_all")]
		public ISingleResult<sp_dim_khuvuc_select_allResult> sp_dim_khuvuc_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_dim_khuvuc_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_khuvuc_select_codangky")]
		public ISingleResult<sp_dim_khuvuc_select_codangkyResult> sp_dim_khuvuc_select_codangky([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHinhThucTuyenSinh", DbType="NVarChar(50)")] string maHinhThucTuyenSinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHinhThucTuyenSinh);
			return ((ISingleResult<sp_dim_khuvuc_select_codangkyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_namtuyensinh_select_all")]
		public ISingleResult<sp_dim_namtuyensinh_select_allResult> sp_dim_namtuyensinh_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_dim_namtuyensinh_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_nganh_select_all")]
		public ISingleResult<sp_dim_nganh_select_allResult> sp_dim_nganh_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_dim_nganh_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_dim_nguontiepcan_select_all")]
		public ISingleResult<sp_dim_nguontiepcan_select_allResult> sp_dim_nguontiepcan_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_dim_nguontiepcan_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_fact_dangky_filter")]
		public ISingleResult<sp_fact_dangky_filterResult> sp_fact_dangky_filter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHinhThuc", DbType="NVarChar(50)")] string maHinhThuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCoSo", DbType="NVarChar(50)")] string maCoSo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNganh", DbType="NVarChar(50)")] string maNganh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhuVuc", DbType="NVarChar(50)")] string maKhuVuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam, maHinhThuc, maCoSo, maNganh, maKhuVuc);
			return ((ISingleResult<sp_fact_dangky_filterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_fact_dangky_tongtheonam")]
		public ISingleResult<sp_fact_dangky_tongtheonamResult> sp_fact_dangky_tongtheonam([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
			return ((ISingleResult<sp_fact_dangky_tongtheonamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_fact_nhaphoc_filter")]
		public ISingleResult<sp_fact_nhaphoc_filterResult> sp_fact_nhaphoc_filter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHinhThuc", DbType="NVarChar(50)")] string maHinhThuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCoSo", DbType="NVarChar(50)")] string maCoSo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaNganh", DbType="NVarChar(50)")] string maNganh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhuVuc", DbType="NVarChar(50)")] string maKhuVuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam, maHinhThuc, maCoSo, maNganh, maKhuVuc);
			return ((ISingleResult<sp_fact_nhaphoc_filterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_fact_nhaphoc_tongtheonam")]
		public ISingleResult<sp_fact_nhaphoc_tongtheonamResult> sp_fact_nhaphoc_tongtheonam([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
			return ((ISingleResult<sp_fact_nhaphoc_tongtheonamResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_googleaccount_exit", IsComposable=true)]
		public object sp_googleaccount_exit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_insert_login_activity")]
		public void sp_insert_login_activity([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateTimeLogin", DbType="DateTime")] System.Nullable<System.DateTime> dateTimeLogin)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, dateTimeLogin);
		}
	}
	
	public partial class sp_dim_coso_select_allResult
	{
		
		private long _CoSoKey;
		
		private string _TenCoSo;
		
		private string _MaCoSo;
		
		public sp_dim_coso_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoSoKey", DbType="BigInt NOT NULL")]
		public long CoSoKey
		{
			get
			{
				return this._CoSoKey;
			}
			set
			{
				if ((this._CoSoKey != value))
				{
					this._CoSoKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCoSo", DbType="NVarChar(50)")]
		public string TenCoSo
		{
			get
			{
				return this._TenCoSo;
			}
			set
			{
				if ((this._TenCoSo != value))
				{
					this._TenCoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCoSo", DbType="NVarChar(50)")]
		public string MaCoSo
		{
			get
			{
				return this._MaCoSo;
			}
			set
			{
				if ((this._MaCoSo != value))
				{
					this._MaCoSo = value;
				}
			}
		}
	}
	
	public partial class sp_tonghop_nguontiepcanResult
	{
		
		private System.Nullable<int> _SoLuong;
		
		public sp_tonghop_nguontiepcanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
	}
	
	public partial class sp_dim_hinhthuctuyensinh_select_allResult
	{
		
		private long _HinhThucKey;
		
		private string _TenHinhThuc;
		
		private System.Nullable<int> _MaHinhThuc;
		
		public sp_dim_hinhthuctuyensinh_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucKey", DbType="BigInt NOT NULL")]
		public long HinhThucKey
		{
			get
			{
				return this._HinhThucKey;
			}
			set
			{
				if ((this._HinhThucKey != value))
				{
					this._HinhThucKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinhThuc", DbType="NVarChar(50)")]
		public string TenHinhThuc
		{
			get
			{
				return this._TenHinhThuc;
			}
			set
			{
				if ((this._TenHinhThuc != value))
				{
					this._TenHinhThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThuc", DbType="Int")]
		public System.Nullable<int> MaHinhThuc
		{
			get
			{
				return this._MaHinhThuc;
			}
			set
			{
				if ((this._MaHinhThuc != value))
				{
					this._MaHinhThuc = value;
				}
			}
		}
	}
	
	public partial class sp_dim_khuvuc_select_allResult
	{
		
		private long _KhuVucKey;
		
		private string _TenKhuVuc;
		
		private string _MaKhuVuc;
		
		public sp_dim_khuvuc_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVucKey", DbType="BigInt NOT NULL")]
		public long KhuVucKey
		{
			get
			{
				return this._KhuVucKey;
			}
			set
			{
				if ((this._KhuVucKey != value))
				{
					this._KhuVucKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhuVuc", DbType="NVarChar(150)")]
		public string TenKhuVuc
		{
			get
			{
				return this._TenKhuVuc;
			}
			set
			{
				if ((this._TenKhuVuc != value))
				{
					this._TenKhuVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuVuc", DbType="NVarChar(50)")]
		public string MaKhuVuc
		{
			get
			{
				return this._MaKhuVuc;
			}
			set
			{
				if ((this._MaKhuVuc != value))
				{
					this._MaKhuVuc = value;
				}
			}
		}
	}
	
	public partial class sp_dim_khuvuc_select_codangkyResult
	{
		
		private string _MaKhuVuc;
		
		private string _TenKhuVuc;
		
		public sp_dim_khuvuc_select_codangkyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuVuc", DbType="NVarChar(50)")]
		public string MaKhuVuc
		{
			get
			{
				return this._MaKhuVuc;
			}
			set
			{
				if ((this._MaKhuVuc != value))
				{
					this._MaKhuVuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhuVuc", DbType="NVarChar(150)")]
		public string TenKhuVuc
		{
			get
			{
				return this._TenKhuVuc;
			}
			set
			{
				if ((this._TenKhuVuc != value))
				{
					this._TenKhuVuc = value;
				}
			}
		}
	}
	
	public partial class sp_dim_namtuyensinh_select_allResult
	{
		
		private long _NamKey;
		
		private System.Nullable<int> _Nam;
		
		private string _TenNam;
		
		public sp_dim_namtuyensinh_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamKey", DbType="BigInt NOT NULL")]
		public long NamKey
		{
			get
			{
				return this._NamKey;
			}
			set
			{
				if ((this._NamKey != value))
				{
					this._NamKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNam", DbType="NVarChar(50)")]
		public string TenNam
		{
			get
			{
				return this._TenNam;
			}
			set
			{
				if ((this._TenNam != value))
				{
					this._TenNam = value;
				}
			}
		}
	}
	
	public partial class sp_dim_nganh_select_allResult
	{
		
		private long _NganhKey;
		
		private string _MaNganh;
		
		private string _TenNganh;
		
		public sp_dim_nganh_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhKey", DbType="BigInt NOT NULL")]
		public long NganhKey
		{
			get
			{
				return this._NganhKey;
			}
			set
			{
				if ((this._NganhKey != value))
				{
					this._NganhKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="NVarChar(50)")]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					this._MaNganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganh", DbType="NVarChar(100)")]
		public string TenNganh
		{
			get
			{
				return this._TenNganh;
			}
			set
			{
				if ((this._TenNganh != value))
				{
					this._TenNganh = value;
				}
			}
		}
	}
	
	public partial class sp_dim_nguontiepcan_select_allResult
	{
		
		private System.Nullable<long> _ID;
		
		private string _TenNguon;
		
		private string _MaNguon;
		
		public sp_dim_nguontiepcan_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt")]
		public System.Nullable<long> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguon", DbType="NVarChar(250)")]
		public string TenNguon
		{
			get
			{
				return this._TenNguon;
			}
			set
			{
				if ((this._TenNguon != value))
				{
					this._TenNguon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguon", DbType="NVarChar(50)")]
		public string MaNguon
		{
			get
			{
				return this._MaNguon;
			}
			set
			{
				if ((this._MaNguon != value))
				{
					this._MaNguon = value;
				}
			}
		}
	}
	
	public partial class sp_fact_dangky_filterResult
	{
		
		private System.Nullable<int> _TongSo;
		
		public sp_fact_dangky_filterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSo", DbType="Int")]
		public System.Nullable<int> TongSo
		{
			get
			{
				return this._TongSo;
			}
			set
			{
				if ((this._TongSo != value))
				{
					this._TongSo = value;
				}
			}
		}
	}
	
	public partial class sp_fact_dangky_tongtheonamResult
	{
		
		private System.Nullable<int> _TongSo;
		
		public sp_fact_dangky_tongtheonamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSo", DbType="Int")]
		public System.Nullable<int> TongSo
		{
			get
			{
				return this._TongSo;
			}
			set
			{
				if ((this._TongSo != value))
				{
					this._TongSo = value;
				}
			}
		}
	}
	
	public partial class sp_fact_nhaphoc_filterResult
	{
		
		private System.Nullable<int> _TongSo;
		
		public sp_fact_nhaphoc_filterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSo", DbType="Int")]
		public System.Nullable<int> TongSo
		{
			get
			{
				return this._TongSo;
			}
			set
			{
				if ((this._TongSo != value))
				{
					this._TongSo = value;
				}
			}
		}
	}
	
	public partial class sp_fact_nhaphoc_tongtheonamResult
	{
		
		private System.Nullable<int> _TongSo;
		
		public sp_fact_nhaphoc_tongtheonamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSo", DbType="Int")]
		public System.Nullable<int> TongSo
		{
			get
			{
				return this._TongSo;
			}
			set
			{
				if ((this._TongSo != value))
				{
					this._TongSo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
